"""Schéma : migrations Alembic fidèles à models.py, contraintes, cascade, dates."""

import sqlite3

import pytest
from alembic import command
from alembic.script import ScriptDirectory
from sqlalchemy import text
from sqlalchemy.exc import IntegrityError

from database import candidatures_db, entreprises_db
from database.connexion import SessionLocal, creer_moteur, engine
from database.models import Base, Candidature, Profil, User
from database.schema import config_alembic


def test_upgrade_head_puis_check_sans_difference(tmp_path):
    url = f"sqlite:///{tmp_path / 'vide.db'}"
    cfg = config_alembic(url)
    command.upgrade(cfg, "head")
    command.check(cfg)   # lève AutogenerateDiffsDetected si models.py diffère

    tables = {r[0] for r in sqlite3.connect(tmp_path / "vide.db").execute(
        "SELECT name FROM sqlite_master WHERE type='table'")}
    assert tables == set(Base.metadata.tables) | {"alembic_version"}


def test_downgrade_base_puis_upgrade(tmp_path):
    cfg = config_alembic(f"sqlite:///{tmp_path / 'aller_retour.db'}")
    command.upgrade(cfg, "head")
    command.downgrade(cfg, "base")
    command.upgrade(cfg, "head")
    command.check(cfg)


def _user(db, email="a@test.fr"):
    u = User(email=email, mot_de_passe_hash="x")
    db.add(u)
    db.commit()
    return u.id


def test_candidature_unique_par_user_mode_ref():
    db = SessionLocal()
    try:
        uid = _user(db)
        db.add(Candidature(user_id=uid, mode="alternance", ref_offre="r1"))
        db.add(Candidature(user_id=uid, mode="job", ref_offre="r1"))   # autre mode : permis
        db.commit()
        db.add(Candidature(user_id=uid, mode="alternance", ref_offre="r1"))
        with pytest.raises(IntegrityError):
            db.commit()
    finally:
        db.close()


def test_suppression_user_en_cascade_cote_base():
    db = SessionLocal()
    try:
        uid = _user(db)
        db.add_all([Profil(user_id=uid), Profil(user_id=uid, mode="job"),
                    Candidature(user_id=uid, ref_offre="r1")])
        db.commit()
        assert [p.mode for p in db.get(User, uid).profils] == ["alternance", "job"]
    finally:
        db.close()
    entreprises_db.ajouter_entreprises(uid, [{"siret": "1", "nom": "ACME"}])

    # DELETE SQL direct, sans l'ORM : seul ON DELETE CASCADE peut nettoyer
    with engine.begin() as cx:
        cx.execute(text("DELETE FROM users WHERE id = :id"), {"id": uid})
        for table in ("profils", "candidatures", "entreprises"):
            assert cx.execute(text(f"SELECT COUNT(*) FROM {table}")).scalar_one() == 0


def test_cles_etrangeres_actives_sur_tout_moteur(tmp_path):
    moteur = creer_moteur(f"sqlite:///{tmp_path / 'fk.db'}")
    with moteur.connect() as cx:
        assert cx.execute(text("PRAGMA foreign_keys")).scalar_one() == 1
    moteur.dispose()


def test_entreprise_mode_par_defaut():
    db = SessionLocal()
    try:
        uid = _user(db)
    finally:
        db.close()
    entreprises_db.ajouter_entreprises(uid, [{"siret": "1"}])
    with engine.connect() as cx:
        assert cx.execute(text("SELECT mode FROM entreprises")).scalar_one() == "alternance"


def test_dates_stockees_en_datetime_et_rendues_en_texte():
    db = SessionLocal()
    try:
        uid = _user(db)
    finally:
        db.close()
    candidatures_db.ajouter_candidature(uid, {"id": "r1", "date_trouvee": "2026-10-01T08:00:00Z"})
    candidatures_db.modifier_candidature(uid, "r1", {"date_candidature": "2026-10-07T15:00:00+00:00"})
    c = candidatures_db.lire_candidature(uid, "r1")
    assert (c["date_trouvee"], c["date_candidature"]) == ("2026-10-01", "2026-10-07")

    entreprises_db.ajouter_entreprises(uid, [{"siret": "1"}])
    liste = entreprises_db.lire_entreprises(uid)
    liste[0].update(mail_envoye=True, mail_envoye_le="2020-01-02 09:30")
    entreprises_db.sauvegarder_entreprises(uid, liste)
    envoyee = entreprises_db.lire_entreprises_envoyees(uid)[0]
    assert envoyee["mail_envoye_le"] == "2020-01-02 09:30"
    assert envoyee["statut_suivi"] == "a_relancer"   # plus de 7 jours

    with engine.connect() as cx:
        types = {r[1]: r[2] for r in cx.execute(text("PRAGMA table_info(candidatures)"))}
    assert types["date_trouvee"] == "DATETIME"


def test_alembic_refuse_une_base_non_geree(tmp_path):
    """L'ancienne base (tables sans alembic_version) n'est jamais migrée en place."""
    chemin = tmp_path / "ancienne.db"
    cx = sqlite3.connect(chemin)
    cx.execute("CREATE TABLE users (id INTEGER PRIMARY KEY)")
    cx.commit()
    cx.close()
    with pytest.raises(RuntimeError, match="pas gérée par Alembic|sans être gérée"):
        command.upgrade(config_alembic(f"sqlite:///{chemin}"), "head")
    tables = {r[0] for r in sqlite3.connect(chemin).execute("SELECT name FROM sqlite_master")}
    assert tables == {"users"}


def test_migration_0002_sur_une_base_en_0001(tmp_path):
    """Cas de data/chasseur_v2.db : base en 0001 avec des données, montée en 0002."""
    chemin = tmp_path / "v2.db"
    cfg = config_alembic(f"sqlite:///{chemin}")
    command.upgrade(cfg, "0001")
    cx = sqlite3.connect(chemin)
    cx.execute("INSERT INTO users (id, email, mot_de_passe_hash) VALUES (1, 'a@test.fr', 'x')")
    cx.execute("INSERT INTO candidatures (user_id, mode, ref_offre, titre) VALUES (1, 'alternance', 'r1', 'Dev')")
    cx.commit()
    cx.close()

    command.upgrade(cfg, "head")
    command.check(cfg)
    cx = sqlite3.connect(chemin)
    assert cx.execute("SELECT ref_offre, titre, lettre_pdf FROM candidatures").fetchall() == [("r1", "Dev", None)]
    tete = ScriptDirectory.from_config(cfg).get_current_head()
    assert cx.execute("SELECT version_num FROM alembic_version").fetchone() == (tete,)
    cx.close()


def test_migration_0004_emails_contactes_par_mode(tmp_path):
    """Base en 0003 avec des adresses contactées : elles passent en mode
    alternance, et l'unicité devient (user_id, mode, email)."""
    chemin = tmp_path / "v3.db"
    cfg = config_alembic(f"sqlite:///{chemin}")
    command.upgrade(cfg, "0003")
    cx = sqlite3.connect(chemin)
    cx.execute("INSERT INTO users (id, email, mot_de_passe_hash) VALUES (1, 'a@test.fr', 'x')")
    cx.execute("INSERT INTO emails_contactes (user_id, email) VALUES (1, 'rh@acme.fr')")
    cx.commit()
    cx.close()

    command.upgrade(cfg, "0004")
    command.check(cfg)
    cx = sqlite3.connect(chemin)
    assert cx.execute("SELECT user_id, mode, email FROM emails_contactes").fetchall() == [(1, "alternance", "rh@acme.fr")]
    cx.execute("INSERT INTO emails_contactes (user_id, mode, email) VALUES (1, 'job', 'rh@acme.fr')")
    with pytest.raises(sqlite3.IntegrityError):
        cx.execute("INSERT INTO emails_contactes (user_id, mode, email) VALUES (1, 'alternance', 'rh@acme.fr')")
    cx.commit()
    cx.close()

    # Retour arrière : une seule ligne par (user_id, email) est gardée
    command.downgrade(cfg, "0003")
    cx = sqlite3.connect(chemin)
    assert cx.execute("SELECT user_id, email FROM emails_contactes").fetchall() == [(1, "rh@acme.fr")]
    cx.close()
